import Head from "next/head";
import Navbar from "../components/Navbar";
import Description from "../components/Description";
import Gig from "../components/Gig";
import About from "../components/About";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Fiver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <section className=" ">
        {/* Navbar  */}
        <header>
          <Navbar />
        </header>
        <main className="h-screen">
          {/* Hero */}
          <div className="ms:flex">
            {/* Gig */}
            <Gig />
            {/* Description */}
            <Description />
          </div>{" "}
          <section>
            {/* About */}
            {/* <About /> */}
          </section>
        </main>

        <footer>{/* Footer */}</footer>
      </section>
    </div>
  );
}
